################################################################################
# 自动生成的文件。不要编辑！
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cec.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dfsdm.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma2d.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_lptim.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_mmc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_qspi.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smbus.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spdifrx.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_crc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dac.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma2d.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_exti.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmpi2c.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_gpio.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_i2c.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_lptim.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_pwr.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rng.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rtc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_spi.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_tim.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usart.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
../project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_utils.c 

OBJS += \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cec.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dfsdm.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma2d.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_lptim.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_mmc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_qspi.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smbus.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spdifrx.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_crc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dac.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma2d.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_exti.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmpi2c.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_gpio.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_i2c.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_lptim.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_pwr.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rng.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rtc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_spi.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_tim.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usart.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.o \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_utils.o 

C_DEPS += \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cec.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dfsdm.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma2d.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_lptim.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_mmc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_qspi.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smbus.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spdifrx.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_crc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dac.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma2d.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_exti.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmpi2c.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_gpio.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_i2c.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_lptim.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_pwr.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rng.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rtc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_spi.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_tim.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usart.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.d \
./project/libraries/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
project/libraries/STM32F4xx_HAL_Driver/Src/%.o: ../project/libraries/STM32F4xx_HAL_Driver/Src/%.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DSOC_FAMILY_STM32 -DSOC_SERIES_STM32F4 -DUSE_HAL_DRIVER -DSTM32F407xx -I"C:\RT-ThreadStudio\workspace\project\drivers" -I"C:\RT-ThreadStudio\workspace\project\drivers\include" -I"C:\RT-ThreadStudio\workspace\project\drivers\include\config" -I"C:\RT-ThreadStudio\workspace\project\libraries\CMSIS\Device\ST\STM32F4xx\Include" -I"C:\RT-ThreadStudio\workspace\project\libraries\CMSIS\Include" -I"C:\RT-ThreadStudio\workspace\project\libraries\CMSIS\RTOS\Template" -I"C:\RT-ThreadStudio\workspace\project\libraries\STM32F4xx_HAL_Driver\Inc" -I"C:\RT-ThreadStudio\workspace\project\libraries\STM32F4xx_HAL_Driver\Inc\Legacy" -I"C:\RT-ThreadStudio\workspace\project" -I"C:\RT-ThreadStudio\workspace\project\applications" -I"C:\RT-ThreadStudio\workspace\project" -I"C:\RT-ThreadStudio\workspace\project\packages\at_device-latest\class\esp8266" -I"C:\RT-ThreadStudio\workspace\project\packages\at_device-latest\inc" -I"C:\RT-ThreadStudio\workspace\project\packages\cJSON-v1.7.17" -I"C:\RT-ThreadStudio\workspace\project\packages\dht11-latest" -I"C:\RT-ThreadStudio\workspace\project\packages\onenet-latest\inc" -I"C:\RT-ThreadStudio\workspace\project\packages\pahomqtt-latest\MQTTClient-RT" -I"C:\RT-ThreadStudio\workspace\project\packages\pahomqtt-latest\MQTTPacket\src" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\dfs\filesystems\devfs" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\dfs\include" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\drivers\include" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\drivers\sensors" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\finsh" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\legacy\dfs" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\legacy" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\newlib" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\posix\io\poll" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\posix\io\stdio" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\posix\ipc" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\net\at\at_socket" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\net\at\include" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\net\netdev\include" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\net\sal\impl" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\net\sal\include\dfs_net" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\net\sal\include\socket\sys_socket" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\net\sal\include\socket" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\components\net\sal\include" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\include" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\libcpu\arm\common" -I"C:\RT-ThreadStudio\workspace\project\rt-thread\libcpu\arm\cortex-m4" -include"C:\RT-ThreadStudio\workspace\project\rtconfig_preinc.h" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

